version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/
    # expose port 8000 to the host
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
    env_file:
      - .env.example
