# Generated by Django 4.0.4 on 2022-09-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyTracker', '0002_key_isreturned_alter_key_keyholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='isReturned',
        ),
        migrations.RemoveField(
            model_name='key',
            name='keyHolder',
        ),
        migrations.RemoveField(
            model_name='key',
            name='time',
        ),
    ]
