# Generated by Django 4.0.4 on 2022-09-19 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keyTracker', '0003_remove_key_isreturned_remove_key_keyholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='isReturned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='key',
            name='keyHolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='key',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
